#!/bin/sh

set -e

BUILD_DATE="$(date)"
BUILD_HASH=$(git rev-parse HEAD)

VERSION="1.0.0"

NAME=nats-configurator
REGISTRY=allright
IMAGE=$REGISTRY/$NAME

docker buildx build . \
--platform linux/arm64,linux/amd64 \
--build-arg VERSION="$VERSION" --build-arg HASH="$BUILD_HASH" --build-arg BUILD_DATE="$BUILD_DATE" \
--push --progress=plain \
--tag $IMAGE --tag $IMAGE:latest --tag $IMAGE:$VERSION
